services:

  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    secrets:
      - postgres_password
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - n8n_internal

  n8n:
    image: n8nio/n8n:2.27.4
    user: "node"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      DB_POSTGRESDB_MIGRATION_RUN: "true"
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD_FILE: /run/secrets/postgres_password

      N8N_PROTOCOL: https
      N8N_SECURE_COOKIE: "true"
      NODE_ENV: production
      N8N_COMMUNITY_PACKAGES_ENABLED: "true"
      N8N_CUSTOM_EXTENSIONS: "/home/node/.n8n/custom"
      N8N_ENCRYPTION_KEY_FILE: /run/secrets/n8n_encryption_key
      N8N_HOST: dev.oldskooln8n.xyz
      N8N_WEBHOOK_URL: https://dev.oldskooln8n.xyz
      N8N_EDITOR_BASE_URL: https://dev.oldskooln8n.xyz
      N8N_PUBLIC_API_BASE_URL: https://dev.oldskooln8n.xyz
      N8N_TRUST_PROXY: "true"
      N8N_PROXY_HOPS: "1"
      N8N_CONCURRENCY_PRODUCTION_LIMIT: "2"
      N8N_USER_MANAGEMENT_DISABLED: "false"
      N8N_DIAGNOSTICS_ENABLED: "false"
      # N8N_RUNNERS_ENABLED: "true"

      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/google_service_account

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_HEALTH_CHECK_ACTIVE: "true"
    volumes:
      - n8n_data:/home/node/.n8n
      - /opt/n8n-lab/import:/import
      - /opt/secrets:/run/secrets:ro
    networks:
      - n8n_internal

  n8n-worker:
    image: n8nio/n8n:2.27.4
    command: worker
    env_file:
      - .env
    user: "node"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD_FILE: /run/secrets/postgres_password

      N8N_PROTOCOL: https
      N8N_SECURE_COOKIE: "true"
      NODE_ENV: production
      N8N_COMMUNITY_PACKAGES_ENABLED: "true"
      N8N_CUSTOM_EXTENSIONS: "/home/node/.n8n/custom"
      N8N_ENCRYPTION_KEY_FILE: /run/secrets/n8n_encryption_key
      N8N_CONCURRENCY_PRODUCTION_LIMIT: "2"
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/google_service_account


      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_HEALTH_CHECK_ACTIVE: "true"
    volumes:
      - n8n_data:/home/node/.n8n
      - /opt/secrets:/run/secrets:ro
    networks:
      - n8n_internal


  chat-backend:
    build: ./chat-backend
    # ports:
    #   - "8001:8000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - postgres_password
    environment:
      DB_HOST: postgres
      DB_NAME: recipes
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - n8n_internal

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - n8n_internal

  cloudflared:
    image: cloudflare/cloudflared:2024.12.0
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    networks:
      - n8n_internal

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - n8n_internal

  netdata:
    image: netdata/netdata:latest
    restart: unless-stopped
    hostname: homeserver
    ports:
      - "127.0.0.1:19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - n8n_internal

networks:
  n8n_internal:

volumes:
  postgres_data:
  n8n_data:
  redis_data:
  crm_documents:
  ollama_data:
  portainer_data:

secrets:
  postgres_password:
    file: /opt/secrets/postgres_password

  n8n_encryption_key:
    file: /opt/secrets/n8n_encryption_key

  google_service_account:
    file: /opt/secrets/service-account.json
