tunnel: 98dfa966-8429-41d2-984f-a10dae2e860f
credentials-file: /etc/cloudflared/98dfa966-8429-41d2-984f-a10dae2e860f.json

ingress:
  - hostname: oldskooln8n.xyz
    service: http://n8n:5678
    originRequest:
      httpHostHeader: oldskooln8n.xyz
      noTLSVerify: true

  - hostname: portainer.oldskooln8n.xyz
    service: http://portainer:9000

  # - hostname: docs.oldskooln8n.xyz
  #   service: http://doc-engine:8000

  - service: http_status:404
