tunnel: 98dfa966-8429-41d2-984f-a10dae2e860f
credentials-file: /etc/cloudflared/98dfa966-8429-41d2-984f-a10dae2e860f.json

protocol: http2

ingress:
  - hostname: oldskooln8n.xyz
    service: http://n8n:5678
  - service: http_status:404
