FROM nginx:alpine

COPY frontend /usr/share/nginx/html

COPY docker-entrypoint.sh /docker-entrypoint-custom.sh

RUN chmod +x /docker-entrypoint-custom.sh

ENTRYPOINT ["/docker-entrypoint-custom.sh"]

CMD ["nginx", "-g", "daemon off;"]

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
