"""Add generation request ID to recipes

Revision ID: 119168a36428
Revises: 464cdb47bae6
Create Date: 2026-08-24 14:07:29.266892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119168a36428'
down_revision: Union[str, Sequence[str], None] = '464cdb47bae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('generation_request_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'recipes', ['generation_request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='unique')
    op.drop_column('recipes', 'generation_request_id')
    # ### end Alembic commands ###
