"""Add recipe image file id

Revision ID: 6c60963ed624
Revises: df6221f8bdba
Create Date: 2026-09-08 08:39:20.460165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c60963ed624'
down_revision: Union[str, Sequence[str], None] = 'df6221f8bdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_file_id')
    # ### end Alembic commands ###
