"""Add recipe generation criteria

Revision ID: df6221f8bdba
Revises: 119168a36428
Create Date: 2026-09-04 11:08:55.302127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6221f8bdba'
down_revision: Union[str, Sequence[str], None] = '119168a36428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('dish', sa.String(length=200), nullable=True))
    op.add_column('recipes', sa.Column('diet', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('cuisine', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'cuisine')
    op.drop_column('recipes', 'diet')
    op.drop_column('recipes', 'dish')
    # ### end Alembic commands ###
